In [5]:
import json
from pathlib import Path

import pandas as pd

RAW_PATH = Path("../data/raw/corporate_finance_2016_2025.json")
METADATA_PATH = Path("../data/reference/metadata_codes_0003060791.csv")
OUTPUT_PATH = Path("../data/processed/corporate_finance_long.csv")

with RAW_PATH.open(encoding="utf-8") as f:
    payload = json.load(f) # json.load(f) は、JSONファイルをPythonの辞書へ変換
# with を使うと、処理終了時にファイルを自動で閉じる
# payload は、APIレスポンス全体を持つ辞書

values = payload["GET_STATS_DATA"]["STATISTICAL_DATA"]["DATA_INF"]["VALUE"]
# 辞書を階層順にたどり、統計レコードが格納されている VALUE を取り出す
values

[{'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20160',
  '@unit': '百万円',
  '$': '293657106'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20170',
  '@unit': '百万円',
  '$': '305552557'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20180',
  '@unit': '百万円',
  '$': '317442376'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20190',
  '@unit': '百万円',
  '$': '319380812'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20200',
  '@unit': '百万円',
  '$': '337555141'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20210',
  '@unit': '百万円',
  '$': '353244936'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20220',
  '@unit': '百万円',
  '$': '367432474'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20230',
  '@unit': '百万円',
  '$': '388041999'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20240',
  '@unit': '百万円',
  '$': '390816532'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20250',
  '@unit': '百万円',
  '$': '413058326'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20160',
  '@unit': '百万円',
  '$': '55927179'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20170',
  '@unit': '百万円',
  '$': '60931998'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20180',
  '@unit': '百万円',
  '$': '61057202'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20190',
  '@unit': '百万円',
  '$': '57467458'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20200',
  '@unit': '百万円',
  '$': '61557037'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20210',
  '@unit': '百万円',
  '$': '69626082'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20220',
  '@unit': '百万円',
  '$': '71738153'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20230',
  '@unit': '百万円',
  '$': '76096066'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20240',
  '@unit': '百万円',
  '$': '85586946'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20250',
  '@unit': '百万円',
  '$': '84804553'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20160',
  '@unit': '百万円',
  '$': '10273532'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20170',
  '@unit': '百万円',
  '$': '10763946'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20180',
  '@unit': '百万円',
  '$': '10327426'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20190',
  '@unit': '百万円',
  '$': '9691138'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20200',
  '@unit': '百万円',
  '$': '10809784'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20210',
  '@unit': '百万円',
  '$': '10527267'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20220',
  '@unit': '百万円',
  '$': '10479961'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20230',
  '@unit': '百万円',
  '$': '12519022'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20240',
  '@unit': '百万円',
  '$': '10380714'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20250',
  '@unit': '百万円',
  '$': '13575240'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20160',
  '@unit': '百万円',
  '$': '53399221'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20170',
  '@unit': '百万円',
  '$': '56369105'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20180',
  '@unit': '百万円',
  '$': '59708818'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20190',
  '@unit': '百万円',
  '$': '62484971'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20200',
  '@unit': '百万円',
  '$': '68889748'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20210',
  '@unit': '百万円',
  '$': '83895649'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20220',
  '@unit': '百万円',
  '$': '87402441'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20230',
  '@unit': '百万円',
  '$': '91634243'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20240',
  '@unit': '百万円',
  '$': '86069283'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20250',
  '@unit': '百万円',
  '$': '96043480'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20160',
  '@unit': '百万円',
  '$': '16030387'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20170',
  '@unit': '百万円',
  '$': '17510585'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20180',
  '@unit': '百万円',
  '$': '20427526'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20190',
  '@unit': '百万円',
  '$': '21535769'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20200',
  '@unit': '百万円',
  '$': '23670171'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20210',
  '@unit': '百万円',
  '$': '29516298'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20220',
  '@unit': '百万円',
  '$': '27080149'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20230',
  '@unit': '百万円',
  '$': '27152553'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20240',
  '@unit': '百万円',
  '$': '30007146'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20250',
  '@unit': '百万円',
  '$': '28050705'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20160',
  '@unit': '百万円',
  '$': '1727789'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20170',
  '@unit': '百万円',
  '$': '1461535'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20180',
  '@unit': '百万円',
  '$': '1391522'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20190',
  '@unit': '百万円',
  '$': '1011534'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20200',
  '@unit': '百万円',
  '$': '6995137'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20210',
  '@unit': '百万円',
  '$': '2233260'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20220',
  '@unit': '百万円',
  '$': '2192130'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20230',
  '@unit': '百万円',
  '$': '1708152'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20240',
  '@unit': '百万円',
  '$': '2379846'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20250',
  '@unit': '百万円',
  '$': '4003215'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20160',
  '@unit': '百万円',
  '$': '97434823'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20170',
  '@unit': '百万円',
  '$': '101115468'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20180',
  '@unit': '百万円',
  '$': '101683792'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20190',
  '@unit': '百万円',
  '$': '98090703'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20200',
  '@unit': '百万円',
  '$': '99229855'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20210',
  '@unit': '百万円',
  '$': '109467543'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20220',
  '@unit': '百万円',
  '$': '109811993'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20230',
  '@unit': '百万円',
  '$': '114710510'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20240',
  '@unit': '百万円',
  '$': '111413881'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20250',
  '@unit': '百万円',
  '$': '118705448'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20160',
  '@unit': '百万円',
  '$': '53154072'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20170',
  '@unit': '百万円',
  '$': '59853978'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20180',
  '@unit': '百万円',
  '$': '61861303'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20190',
  '@unit': '百万円',
  '$': '59355384'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20200',
  '@unit': '百万円',
  '$': '56940344'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20210',
  '@unit': '百万円',
  '$': '61782235'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20220',
  '@unit': '百万円',
  '$': '67439898'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20230',
  '@unit': '百万円',
  '$': '73683193'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20240',
  '@unit': '百万円',
  '$': '71862018'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20250',
  '@unit': '百万円',
  '$': '74146937'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20160',
  '@unit': '百万円',
  '$': '22534647'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20170',
  '@unit': '百万円',
  '$': '25965752'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20180',
  '@unit': '百万円',
  '$': '21177080'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20190',
  '@unit': '百万円',
  '$': '20999900'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20200',
  '@unit': '百万円',
  '$': '24999805'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20210',
  '@unit': '百万円',
  '$': '27835565'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20220',
  '@unit': '百万円',
  '$': '23279409'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20230',
  '@unit': '百万円',
  '$': '30704287'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20240',
  '@unit': '百万円',
  '$': '28276155'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20250',
  '@unit': '百万円',
  '$': '26812061'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20160',
  '@unit': '百万円',
  '$': '219801873'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20170',
  '@unit': '百万円',
  '$': '230786314'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20180',
  '@unit': '百万円',
  '$': '237795596'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20190',
  '@unit': '百万円',
  '$': '230419567'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20200',
  '@unit': '百万円',
  '$': '209960185'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20210',
  '@unit': '百万円',
  '$': '230967403'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20220',
  '@unit': '百万円',
  '$': '253945331'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20230',
  '@unit': '百万円',
  '$': '258151968'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20240',
  '@unit': '百万円',
  '$': '266587497'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20250',
  '@unit': '百万円',
  '$': '268369147'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20160',
  '@unit': '百万円',
  '$': '65436004'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20170',
  '@unit': '百万円',
  '$': '66075006'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20180',
  '@unit': '百万円',
  '$': '68069986'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20190',
  '@unit': '百万円',
  '$': '64121780'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20200',
  '@unit': '百万円',
  '$': '63672664'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20210',
  '@unit': '百万円',
  '$': '73241110'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20220',
  '@unit': '百万円',
  '$': '74818913'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20230',
  '@unit': '百万円',
  '$': '79797415'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20240',
  '@unit': '百万円',
  '$': '84871648'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20250',
  '@unit': '百万円',
  '$': '87217265'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20160',
  '@unit': '百万円',
  '$': '12488919'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20170',
  '@unit': '百万円',
  '$': '12840016'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20180',
  '@unit': '百万円',
  '$': '12779737'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20190',
  '@unit': '百万円',
  '$': '11763916'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20200',
  '@unit': '百万円',
  '$': '10444109'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20210',
  '@unit': '百万円',
  '$': '11003324'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20220',
  '@unit': '百万円',
  '$': '12064114'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20230',
  '@unit': '百万円',
  '$': '12374585'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20240',
  '@unit': '百万円',
  '$': '12287217'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20250',
  '@unit': '百万円',
  '$': '14533882'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20160',
  '@unit': '百万円',
  '$': '34259944'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20170',
  '@unit': '百万円',
  '$': '36613898'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20180',
  '@unit': '百万円',
  '$': '37117377'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20190',
  '@unit': '百万円',
  '$': '37980464'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20200',
  '@unit': '百万円',
  '$': '36059221'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20210',
  '@unit': '百万円',
  '$': '36524523'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20220',
  '@unit': '百万円',
  '$': '38043105'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20230',
  '@unit': '百万円',
  '$': '39117853'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20240',
  '@unit': '百万円',
  '$': '41827041'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20250',
  '@unit': '百万円',
  '$': '43647876'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20160',
  '@unit': '百万円',
  '$': '17231431'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20170',
  '@unit': '百万円',
  '$': '20930457'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20180',
  '@unit': '百万円',
  '$': '22037053'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20190',
  '@unit': '百万円',
  '$': '22769386'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20200',
  '@unit': '百万円',
  '$': '24075872'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20210',
  '@unit': '百万円',
  '$': '23240045'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20220',
  '@unit': '百万円',
  '$': '22857144'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20230',
  '@unit': '百万円',
  '$': '25246002'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20240',
  '@unit': '百万円',
  '$': '24339911'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20250',
  '@unit': '百万円',
  '$': '24225152'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20160',
  '@unit': '百万円',
  '$': '3325589'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20170',
  '@unit': '百万円',
  '$': '2124009'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20180',
  '@unit': '百万円',
  '$': '3166904'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20190',
  '@unit': '百万円',
  '$': '2307683'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20200',
  '@unit': '百万円',
  '$': '2462723'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20210',
  '@unit': '百万円',
  '$': '2549312'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20220',
  '@unit': '百万円',
  '$': '2917830'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20230',
  '@unit': '百万円',
  '$': '1630110'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20240',
  '@unit': '百万円',
  '$': '2433639'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20250',
  '@unit': '百万円',
  '$': '3404774'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20160',
  '@unit': '百万円',
  '$': '148769488'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20170',
  '@unit': '百万円',
  '$': '161105312'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20180',
  '@unit': '百万円',
  '$': '165728325'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20190',
  '@unit': '百万円',
  '$': '149187099'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20200',
  '@unit': '百万円',
  '$': '134431671'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20210',
  '@unit': '百万円',
  '$': '138522844'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20220',
  '@unit': '百万円',
  '$': '148220253'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20230',
  '@unit': '百万円',
  '$': '143239768'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20240',
  '@unit': '百万円',
  '$': '140897226'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20250',
  '@unit': '百万円',
  '$': '137362839'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20160',
  '@unit': '百万円',
  '$': '115527934'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20170',
  '@unit': '百万円',
  '$': '129547118'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20180',
  '@unit': '百万円',
  '$': '133986661'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20190',
  '@unit': '百万円',
  '$': '128836699'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20200',
  '@unit': '百万円',
  '$': '107592431'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20210',
  '@unit': '百万円',
  '$': '108764218'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20220',
  '@unit': '百万円',
  '$': '119818146'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20230',
  '@unit': '百万円',
  '$': '131228662'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20240',
  '@unit': '百万円',
  '$': '134796812'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20250',
  '@unit': '百万円',
  '$': '138272696'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20160',
  '@unit': '百万円',
  '$': '42629192'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20170',
  '@unit': '百万円',
  '$': '50264496'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20180',
  '@unit': '百万円',
  '$': '36394303'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20190',
  '@unit': '百万円',
  '$': '37818506'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20200',
  '@unit': '百万円',
  '$': '39563580'},
 {'@cat01': '045',

In [6]:
if isinstance(values, dict):
    values = [values]
# isinstance(values, dict) は、values が辞書型かどうかを確認
# 通常、複数件のデータがあるとき、values はリストだが、e-Stat APIでは取得結果が1件だけの場合、
# リストではなく辞書だけが返る場合がある。
# そのままでは、複数件を前提にした後続の処理と形が異なってしまうため、辞書をリストで包む
# このコードによって、データが1件でも複数件でも、常に「レコードのリスト」として扱えるように形を統一する。

values

[{'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20160',
  '@unit': '百万円',
  '$': '293657106'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20170',
  '@unit': '百万円',
  '$': '305552557'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20180',
  '@unit': '百万円',
  '$': '317442376'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20190',
  '@unit': '百万円',
  '$': '319380812'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20200',
  '@unit': '百万円',
  '$': '337555141'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20210',
  '@unit': '百万円',
  '$': '353244936'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20220',
  '@unit': '百万円',
  '$': '367432474'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20230',
  '@unit': '百万円',
  '$': '388041999'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20240',
  '@unit': '百万円',
  '$': '390816532'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20250',
  '@unit': '百万円',
  '$': '413058326'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20160',
  '@unit': '百万円',
  '$': '55927179'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20170',
  '@unit': '百万円',
  '$': '60931998'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20180',
  '@unit': '百万円',
  '$': '61057202'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20190',
  '@unit': '百万円',
  '$': '57467458'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20200',
  '@unit': '百万円',
  '$': '61557037'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20210',
  '@unit': '百万円',
  '$': '69626082'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20220',
  '@unit': '百万円',
  '$': '71738153'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20230',
  '@unit': '百万円',
  '$': '76096066'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20240',
  '@unit': '百万円',
  '$': '85586946'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20250',
  '@unit': '百万円',
  '$': '84804553'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20160',
  '@unit': '百万円',
  '$': '10273532'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20170',
  '@unit': '百万円',
  '$': '10763946'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20180',
  '@unit': '百万円',
  '$': '10327426'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20190',
  '@unit': '百万円',
  '$': '9691138'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20200',
  '@unit': '百万円',
  '$': '10809784'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20210',
  '@unit': '百万円',
  '$': '10527267'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20220',
  '@unit': '百万円',
  '$': '10479961'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20230',
  '@unit': '百万円',
  '$': '12519022'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20240',
  '@unit': '百万円',
  '$': '10380714'},
 {'@cat01': '022',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20250',
  '@unit': '百万円',
  '$': '13575240'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20160',
  '@unit': '百万円',
  '$': '53399221'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20170',
  '@unit': '百万円',
  '$': '56369105'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20180',
  '@unit': '百万円',
  '$': '59708818'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20190',
  '@unit': '百万円',
  '$': '62484971'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20200',
  '@unit': '百万円',
  '$': '68889748'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20210',
  '@unit': '百万円',
  '$': '83895649'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20220',
  '@unit': '百万円',
  '$': '87402441'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20230',
  '@unit': '百万円',
  '$': '91634243'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20240',
  '@unit': '百万円',
  '$': '86069283'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20250',
  '@unit': '百万円',
  '$': '96043480'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20160',
  '@unit': '百万円',
  '$': '16030387'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20170',
  '@unit': '百万円',
  '$': '17510585'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20180',
  '@unit': '百万円',
  '$': '20427526'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20190',
  '@unit': '百万円',
  '$': '21535769'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20200',
  '@unit': '百万円',
  '$': '23670171'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20210',
  '@unit': '百万円',
  '$': '29516298'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20220',
  '@unit': '百万円',
  '$': '27080149'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20230',
  '@unit': '百万円',
  '$': '27152553'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20240',
  '@unit': '百万円',
  '$': '30007146'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20250',
  '@unit': '百万円',
  '$': '28050705'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20160',
  '@unit': '百万円',
  '$': '1727789'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20170',
  '@unit': '百万円',
  '$': '1461535'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20180',
  '@unit': '百万円',
  '$': '1391522'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20190',
  '@unit': '百万円',
  '$': '1011534'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20200',
  '@unit': '百万円',
  '$': '6995137'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20210',
  '@unit': '百万円',
  '$': '2233260'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20220',
  '@unit': '百万円',
  '$': '2192130'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20230',
  '@unit': '百万円',
  '$': '1708152'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20240',
  '@unit': '百万円',
  '$': '2379846'},
 {'@cat01': '022',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20250',
  '@unit': '百万円',
  '$': '4003215'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20160',
  '@unit': '百万円',
  '$': '97434823'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20170',
  '@unit': '百万円',
  '$': '101115468'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20180',
  '@unit': '百万円',
  '$': '101683792'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20190',
  '@unit': '百万円',
  '$': '98090703'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20200',
  '@unit': '百万円',
  '$': '99229855'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20210',
  '@unit': '百万円',
  '$': '109467543'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20220',
  '@unit': '百万円',
  '$': '109811993'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20230',
  '@unit': '百万円',
  '$': '114710510'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20240',
  '@unit': '百万円',
  '$': '111413881'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20250',
  '@unit': '百万円',
  '$': '118705448'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20160',
  '@unit': '百万円',
  '$': '53154072'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20170',
  '@unit': '百万円',
  '$': '59853978'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20180',
  '@unit': '百万円',
  '$': '61861303'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20190',
  '@unit': '百万円',
  '$': '59355384'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20200',
  '@unit': '百万円',
  '$': '56940344'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20210',
  '@unit': '百万円',
  '$': '61782235'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20220',
  '@unit': '百万円',
  '$': '67439898'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20230',
  '@unit': '百万円',
  '$': '73683193'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20240',
  '@unit': '百万円',
  '$': '71862018'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20250',
  '@unit': '百万円',
  '$': '74146937'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20160',
  '@unit': '百万円',
  '$': '22534647'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20170',
  '@unit': '百万円',
  '$': '25965752'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20180',
  '@unit': '百万円',
  '$': '21177080'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20190',
  '@unit': '百万円',
  '$': '20999900'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20200',
  '@unit': '百万円',
  '$': '24999805'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20210',
  '@unit': '百万円',
  '$': '27835565'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20220',
  '@unit': '百万円',
  '$': '23279409'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20230',
  '@unit': '百万円',
  '$': '30704287'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20240',
  '@unit': '百万円',
  '$': '28276155'},
 {'@cat01': '022',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20250',
  '@unit': '百万円',
  '$': '26812061'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20160',
  '@unit': '百万円',
  '$': '219801873'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20170',
  '@unit': '百万円',
  '$': '230786314'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20180',
  '@unit': '百万円',
  '$': '237795596'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20190',
  '@unit': '百万円',
  '$': '230419567'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20200',
  '@unit': '百万円',
  '$': '209960185'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20210',
  '@unit': '百万円',
  '$': '230967403'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20220',
  '@unit': '百万円',
  '$': '253945331'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20230',
  '@unit': '百万円',
  '$': '258151968'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20240',
  '@unit': '百万円',
  '$': '266587497'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '25',
  '@time': '20250',
  '@unit': '百万円',
  '$': '268369147'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20160',
  '@unit': '百万円',
  '$': '65436004'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20170',
  '@unit': '百万円',
  '$': '66075006'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20180',
  '@unit': '百万円',
  '$': '68069986'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20190',
  '@unit': '百万円',
  '$': '64121780'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20200',
  '@unit': '百万円',
  '$': '63672664'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20210',
  '@unit': '百万円',
  '$': '73241110'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20220',
  '@unit': '百万円',
  '$': '74818913'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20230',
  '@unit': '百万円',
  '$': '79797415'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20240',
  '@unit': '百万円',
  '$': '84871648'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '24',
  '@time': '20250',
  '@unit': '百万円',
  '$': '87217265'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20160',
  '@unit': '百万円',
  '$': '12488919'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20170',
  '@unit': '百万円',
  '$': '12840016'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20180',
  '@unit': '百万円',
  '$': '12779737'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20190',
  '@unit': '百万円',
  '$': '11763916'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20200',
  '@unit': '百万円',
  '$': '10444109'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20210',
  '@unit': '百万円',
  '$': '11003324'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20220',
  '@unit': '百万円',
  '$': '12064114'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20230',
  '@unit': '百万円',
  '$': '12374585'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20240',
  '@unit': '百万円',
  '$': '12287217'},
 {'@cat01': '045',
  '@cat02': '108',
  '@cat03': '16',
  '@time': '20250',
  '@unit': '百万円',
  '$': '14533882'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20160',
  '@unit': '百万円',
  '$': '34259944'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20170',
  '@unit': '百万円',
  '$': '36613898'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20180',
  '@unit': '百万円',
  '$': '37117377'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20190',
  '@unit': '百万円',
  '$': '37980464'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20200',
  '@unit': '百万円',
  '$': '36059221'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20210',
  '@unit': '百万円',
  '$': '36524523'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20220',
  '@unit': '百万円',
  '$': '38043105'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20230',
  '@unit': '百万円',
  '$': '39117853'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20240',
  '@unit': '百万円',
  '$': '41827041'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '25',
  '@time': '20250',
  '@unit': '百万円',
  '$': '43647876'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20160',
  '@unit': '百万円',
  '$': '17231431'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20170',
  '@unit': '百万円',
  '$': '20930457'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20180',
  '@unit': '百万円',
  '$': '22037053'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20190',
  '@unit': '百万円',
  '$': '22769386'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20200',
  '@unit': '百万円',
  '$': '24075872'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20210',
  '@unit': '百万円',
  '$': '23240045'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20220',
  '@unit': '百万円',
  '$': '22857144'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20230',
  '@unit': '百万円',
  '$': '25246002'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20240',
  '@unit': '百万円',
  '$': '24339911'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '24',
  '@time': '20250',
  '@unit': '百万円',
  '$': '24225152'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20160',
  '@unit': '百万円',
  '$': '3325589'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20170',
  '@unit': '百万円',
  '$': '2124009'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20180',
  '@unit': '百万円',
  '$': '3166904'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20190',
  '@unit': '百万円',
  '$': '2307683'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20200',
  '@unit': '百万円',
  '$': '2462723'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20210',
  '@unit': '百万円',
  '$': '2549312'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20220',
  '@unit': '百万円',
  '$': '2917830'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20230',
  '@unit': '百万円',
  '$': '1630110'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20240',
  '@unit': '百万円',
  '$': '2433639'},
 {'@cat01': '045',
  '@cat02': '142',
  '@cat03': '16',
  '@time': '20250',
  '@unit': '百万円',
  '$': '3404774'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20160',
  '@unit': '百万円',
  '$': '148769488'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20170',
  '@unit': '百万円',
  '$': '161105312'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20180',
  '@unit': '百万円',
  '$': '165728325'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20190',
  '@unit': '百万円',
  '$': '149187099'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20200',
  '@unit': '百万円',
  '$': '134431671'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20210',
  '@unit': '百万円',
  '$': '138522844'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20220',
  '@unit': '百万円',
  '$': '148220253'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20230',
  '@unit': '百万円',
  '$': '143239768'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20240',
  '@unit': '百万円',
  '$': '140897226'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '25',
  '@time': '20250',
  '@unit': '百万円',
  '$': '137362839'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20160',
  '@unit': '百万円',
  '$': '115527934'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20170',
  '@unit': '百万円',
  '$': '129547118'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20180',
  '@unit': '百万円',
  '$': '133986661'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20190',
  '@unit': '百万円',
  '$': '128836699'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20200',
  '@unit': '百万円',
  '$': '107592431'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20210',
  '@unit': '百万円',
  '$': '108764218'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20220',
  '@unit': '百万円',
  '$': '119818146'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20230',
  '@unit': '百万円',
  '$': '131228662'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20240',
  '@unit': '百万円',
  '$': '134796812'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '24',
  '@time': '20250',
  '@unit': '百万円',
  '$': '138272696'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20160',
  '@unit': '百万円',
  '$': '42629192'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20170',
  '@unit': '百万円',
  '$': '50264496'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20180',
  '@unit': '百万円',
  '$': '36394303'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20190',
  '@unit': '百万円',
  '$': '37818506'},
 {'@cat01': '045',
  '@cat02': '129',
  '@cat03': '16',
  '@time': '20200',
  '@unit': '百万円',
  '$': '39563580'},
 {'@cat01': '045',

In [7]:
df = pd.DataFrame(values).rename(
    columns={
        "@cat01": "item_code",# 財務項目コード
        "@cat02": "industry_code",# 業種コード
        "@cat03": "capital_size_code",# 資本金規模コード
        "@time": "time_code",# 年度コード
        "@unit": "unit",
        "$": "amount",# 金額
    }
)
df

    item_code industry_code capital_size_code time_code unit     amount
0         022           108                25     20160  百万円  293657106
1         022           108                25     20170  百万円  305552557
2         022           108                25     20180  百万円  317442376
3         022           108                25     20190  百万円  319380812
4         022           108                25     20200  百万円  337555141
..        ...           ...               ...       ...  ...        ...
535       157           129                16     20210  百万円    4029975
536       157           129                16     20220  百万円    4333883
537       157           129                16     20230  百万円    3249057
538       157           129                16     20240  百万円    5014268
539       157           129                16     20250  百万円    4833948

[540 rows x 6 columns]

In [8]:
metadata = pd.read_csv(METADATA_PATH, dtype=str)
# dtype=strによって文字列として認識
# なぜ文字列とするか？⇒例えば045を数値として読むと45になり、先頭のゼロが消える。
# すると、APIデータの 045 と正しく結合できなくなってしまう

metadata

    class_id           class_name   code            name level unit
0      cat01  調査項目 (金融業、保険業以外の業種)    001        母集団(当期末)     1    社
1      cat01  調査項目 (金融業、保険業以外の業種)    002  現金・預金(当期末流動資産)     1  百万円
2      cat01  調査項目 (金融業、保険業以外の業種)    003   受取手形(当期末流動資産)     1  百万円
3      cat01  調査項目 (金融業、保険業以外の業種)    004    売掛金(当期末流動資産)     1  百万円
4      cat01  調査項目 (金融業、保険業以外の業種)    005     株式(当期末流動資産)     1  百万円
..       ...                  ...    ...             ...   ...  ...
371     time                 年  期  20210          2021年度     1  NaN
372     time                 年  期  20220          2022年度     1  NaN
373     time                 年  期  20230          2023年度     1  NaN
374     time                 年  期  20240          2024年度     1  NaN
375     time                 年  期  20250          2025年度     1  NaN

[376 rows x 6 columns]

In [9]:
def create_name_mapping(class_id: str) -> dict[str, str]:
    target = metadata.loc[
        metadata["class_id"] == class_id,# 引数のclass_idと同じclass_id
        ["code", "name"],
    ].drop_duplicates()

    return dict(zip(target["code"], target["name"]))
# zip()は複数のイテラブル（リストやタプルなど）の要素を同じインデックス（順番）ごとにまとめてペアを作る組み込み関数

item_mapping = create_name_mapping("cat01")
industry_mapping = create_name_mapping("cat02")
capital_size_mapping = create_name_mapping("cat03")
time_mapping = create_name_mapping("time")

print(item_mapping)
print(industry_mapping)
print(capital_size_mapping)
print(time_mapping)

{'001': '母集団(当期末)', '002': '現金・預金(当期末流動資産)', '003': '受取手形(当期末流動資産)', '004': '売掛金(当期末流動資産)', '005': '株式(当期末流動資産)', '006': '公社債(当期末流動資産)', '007': 'その他の有価証券(当期末流動資産)', '008': '製品又は商品(当期末流動資産)', '009': '仕掛品(当期末流動資産)', '010': '原材料・貯蔵品(当期末流動資産)', '011': 'その他流動資産(当期末流動資産)', '012': '土地(当期末固定資産)', '013': '建設仮勘定(当期末固定資産)', '014': 'その他の有形固定資産(当期末固定資産)', '015': 'ソフトウェアを除く無形固定資産(当期末固定資産)', '016': 'ソフトウェア(当期末固定資産)', '217': '無形固定資産計(当期末固定資産)', '017': '株式(当期末固定資産)', '018': '公社債(当期末固定資産)', '019': 'その他の有価証券(当期末固定資産)', '020': 'その他投資(当期末固定資産)', '021': '繰延資産(当期末)', '022': '資産合計(当期末)', '023': '受取手形割引残高(当期末)', '024': '支払手形(当期末流動負債)', '025': '買掛金(当期末流動負債)', '026': '金融機関借入金(当期末流動負債)', '027': 'その他の借入金(当期末流動負債)', '028': '引当金(当期末流動負債)', '029': 'その他流動負債(当期末流動負債)', '030': '社債(当期末固定負債)', '031': '金融機関借入金(当期末固定負債)', '032': 'その他の借入金(当期末固定負債)', '033': '引当金(当期末固定負債)', '034': 'その他固定負債(当期末固定負債)', '035': '特別法上の準備金(当期末)', '036': '資本金(当期末)', '037': '資本準備金(当期末)', '039': 'その他資本剰余金(当期末)', '038': '利益準備金(当期末)', '040': '積立金(当期末)', '041': '繰越利益剰余金(当期末)', '219': '自己株式(当期末)', '218': 'その他(当期末)', '234': '新株予約権(当期末)', '042': '負債及び純資産合計(当期末)', '043': '関係会社売掛金(当期末)', '044': '関係会社買掛金(当期末)', '045': '売上高(当期末)', '046': '売上原価(当期末)', '047': '販売費及び一般管理費(当期末)', '048': '営業利益(当期末)', '049': '営業外収益(当期末)', '050': '営業外費用(当期末)', '051': '経常利益(当期末)', '052': '特別利益(当期末)', '053': '特別損失(当期末)', '054': '税引前当期純利益(当期末)', '055': '法人税、住民税及び事業税(当期末)', '056': '当期純利益(当期末)', '220': '法人税等調整額(当期末)', '058': '中間配当額(当期末)', '059': '配当金(当期末)', '060': '配当金計(当期末)', '061': '社内留保(当期末)', '062': '減価償却費(当期末)', '063': '特別減価償却費(当期末)', '221': '減価償却費計', '065': '役員給与(当期末)', '057': '役員賞与(当期末)', '066': '従業員給与(当期末)', '235': '従業員賞与(当期末)', '067': '福利厚生費(当期末)', '068': '支払利息等(当期末)', '069': '動産・不動産賃借料(当期末)', '070': '租税公課(当期末)', '071': '期中平均役員数(当期末)', '072': '期中平均従業員数(当期末)', '073': '付加価値(当期末)', '074': '営業純益(当期末)', '075': '在庫投資(当期末投資)', '076': '製品又は商品(当期末資金需給)', '077': '仕掛品(当期末資金需給)', '078': '原材料・貯蔵品(当期末資金需給)', '080': '建設仮勘定(当期末資金需給)', '081': 'その他の有形固定資産(当期末資金需給)', '085': '実物投資(当期末資金需給)', '086': 'ソフトウェアを除く設備投資(当期末資金需給)', '087': '土地(当期末資金需給)', '088': '在庫投資(当期末資金需給)', '089': '投融資等(当期末資金需給)', '090': '株式(当期末資金需給)', '091': '公社債(当期末資金需給)', '092': '融資その他(当期末資金需給)', '093': '無形固定資産(当期末資金需給)', '094': '与信超、受信超(当期末資金需給)', '095': '当座資産(当期末資金需給)', '096': '現金・預金(当期末資金需給)', '097': '一時有価(当期末資金需給)', '098': 'その他資産(当期末資金需給)', '099': '資金運用計(当期末資金需給)', '100': '自己資金(当期末資金需給)', '101': '資本金(当期末資金需給)', '102': '資本準備金(当期末資金需給)', '103': '利益留保(当期末資金需給)', '104': '引当金等(当期末資金需給)', '105': '特別法上の準備金(当期末資本需給)', '106': '社債(当期末資金需給)', '107': '長期借入金(当期末資金需給)', '108': '長期金融機関借入金(当期末資金需給)', '109': '長期その他借入金(当期末資金需給)', '110': '短期借入金(当期末資金需給)', '111': '短期金融機関借入金(当期末資金需給)', '112': '短期その他借入金(当期末資金需給)', '113': 'その他負債(当期末資金需給)', '114': '売掛金(当期末資金需給)', '115': '受取手形(当期末資金需給)', '116': '受取手形割引残高(当期末資金需給)', '117': '買掛金(当期末資金需給)', '118': '支払手形(当期末資金需給)', '222': 'その他の純資産(当期末資金需給)', '223': '自己株式(当期末資金需給)', '240': '新株予約権(当期末資金需給)', '119': '当座比率(当期末)', '120': '流動比率(当期末)', '121': '固定比率(当期末)', '122': '自己資本比率(当期末)', '123': '総資本営業利益率(当期末)', '124': '総資本経常利益率(当期末)', '125': '自己資本経常利益率(当期末)', '126': '売上高営業利益率(当期末)', '127': '売上高経常利益率(当期末)', '128': '総資本回転率(当期末)', '129': '有形固定資産回転率(当期末)', '130': '棚卸資産回転期間(当期末)', '131': '売上債権回転期間(当期末)', '132': '買入債務回転期間(当期末)', '133': '信用供与率(当期末)', '134': '手元流動性(当期末)', '135': '借入金利子率(当期末)', '136': '減価償却率(当期末)', '137': '配当率(当期末)', '138': '配当性向(当期末)', '139': '内部留保率_Ｈ１８年度以前(当期末)', '241': '内部留保率_Ｈ１９年度以降(当期末)', '140': '付加価値率(当期末)', '141': '従業員一人当付加価値(当期末)', '142': '労働装備率(当期末)', '143': '設備投資効率(当期末)', '144': '流動資産(当期末)', '145': '有価証券(当期末)', '146': '棚卸資産(当期末)', '147': '固定資産(当期末)', '148': '有形固定資産(当期末)', '149': '無形固定資産(当期末)', '150': '投資その他の資産(当期末)', '151': '投資有価証券(当期末)', '152': '流動負債(当期末)', '153': '短期借入金(当期末)', '154': '固定負債(当期末)', '155': '長期借入金(当期末)', '224': '負債(当期末)', '157': '純資産(当期末)', '225': '資本剰余金(当期末)', '226': '利益剰余金(当期末)', '237': '株主資本(当期末)', '239': 'その他利益剰余金(当期末)', '159': '現金・預金(前期末流動資産)', '160': '受取手形(前期末流動資産)', '161': '売掛金(前期末流動資産)', '162': '株式(前期末流動資産)', '163': '公社債(前期末流動資産)', '164': 'その他の有価証券(前期末流動資産)', '165': '製品又は商品(前期末流動資産)', '166': '仕掛品(前期末流動資産)', '167': '原材料・貯蔵品(前期末流動資産)', '168': 'その他流動資産(前期末流動資産)', '169': '土地(前期末固定資産)', '170': '建設仮勘定(前期末固定資産)', '171': 'その他の有形固定資産(前期末固定資産)', '172': 'ソフトウェアを除く無形固定資産(前期末固定資産)', '173': 'ソフトウェア(前期末固定資産)', '227': '無形固定資産計(前期末固定資産)', '174': '株式(前期末固定資産)', '175': '公社債(前期末固定資産)', '176': 'その他の有価証券(前期末固定資産)', '177': 'その他投資(前期末固定資産)', '178': '繰延資産(前期末)', '179': '資産合計(前期末)', '180': '受取手形割引残高(前期末)', '181': '支払手形(前期末流動負債)', '182': '買掛金(前期末流動負債)', '183': '金融機関借入金(前期末流動負債)', '184': 'その他の借入金(前期末流動負債)', '185': '引当金(前期末流動負債)', '186': 'その他流動負債(前期末流動負債)', '187': '社債(前期末固定負債)', '188': '金融機関借入金(前期末固定負債)', '189': 'その他の借入金(前期末固定負債)', '190': '引当金(前期末固定負債)', '191': 'その他固定負債(前期末固定負債)', '192': '特別法上の準備金(前期末)', '193': '資本金(前期末)', '194': '資本準備金(前期末)', '196': 'その他資本剰余金(前期末)', '195': '利益準備金(前期末)', '197': '積立金(前期末)', '198': '繰越利益剰余金(前期末)', '229': '自己株式(前期末)', '228': 'その他(前期末)', '233': '新株予約権(前期末)', '199': '負債及び純資産合計(前期末)', '200': '関係会社売掛金(前期末)', '201': '関係会社買掛金(前期末)', '202': '流動資産(前期末)', '203': '有価証券(前期末)', '204': '棚卸資産(前期末)', '205': '固定資産(前期末)', '206': '有形固定資産(前期末)', '207': '無形固定資産(前期末)', '208': '投資その他の資産(前期末)', '209': '投資有価証券(前期末)', '210': '流動負債(前期末)', '211': '短期借入金(前期末)', '212': '固定負債(前期末)', '213': '長期借入金(前期末)', '230': '負債(前期末)', '215': '純資産(前期末)', '231': '資本剰余金(前期末)', '232': '利益剰余金(前期末)', '236': '株主資本(前期末)', '238': 'その他利益剰余金(前期末)'}
{'104': '全産業（除く金融保険業）', '108': '製造業', '109': '食料品製造業', '110': '繊維工業', '163': '繊維工業(H20年度まで)', '111': '衣服・その他の繊維製品製造業(H20年度まで)', '112': '木材・木製品製造業', '113': 'パルプ・紙・紙加工品製造業', '114': '印刷・同関連業', '115': '化学工業', '116': '石油製品・石炭製品製造業', '117': '窯業・土石製品製造業', '118': '鉄鋼業', '119': '非鉄金属製造業', '120': '金属製品製造業', '154': 'はん用機械器具製造業', '121': '生産用機械器具製造業', '124': '業務用機械器具製造業', '122': '電気機械器具製造業', '145': '情報通信機械器具製造業', '146': '輸送用機械器具製造業(集約)', '123': '自動車・同附属品製造業', '125': 'その他の輸送用機械器具製造業', '126': 'その他の製造業', '144': '非製造業', '105': '農林水産業(集約)', '101': '農業、林業', '162': '農業(H20年度まで)', '102': '林業(H20年度まで)', '103': '漁業', '106': '鉱業、採石業、砂利採取業', '107': '建設業', '135': '電気業', '136': 'ガス・熱供給・水道業', '142': '情報通信業', '134': '運輸業、郵便業(集約)', '131': '陸運業', '132': '水運業', '133': 'その他の運輸業', '129': '卸売業・小売業(集約)', '127': '卸売業', '128': '小売業', '155': '不動産業、物品賃貸業(集約)', '130': '不動産業', '149': '物品賃貸業(集約)', '150': 'リース業', '151': 'その他の物品賃貸業', '137': 'サービス業(集約)', '156': '宿泊業、飲食サービス業(集約)', '139': '宿泊業', '148': '飲食サービス業', '157': '生活関連サービス業、娯楽業(集約)', '140': '生活関連サービス業', '141': '娯楽業', '161': '学術研究、専門・技術サービス業(集約)', '138': '広告業', '158': '純粋持株会社', '159': 'その他の学術研究、専門・技術サービス業', '153': '教育、学習支援業', '152': '医療、福祉業', '160': '職業紹介・労働者派遣業', '143': 'その他のサービス業'}
{'26': '全規模', '25': '10億円以上', '24': '1億円以上 - 10億円未満', '21': '5千万円以上 - 1億円未満', '19': '1千万円以上 - 1億円未満', '18': '1千万円以上 - 5千万円未満', '16': '1千万円未満', '23': '1億円以上', '22': '1億円未満', '20': '2千万円以上 - 5千万円未満', '17': '1千万円以上 - 2千万円未満', '15': '5百万円以上 - 1千万円未満', '14': '3百万円以上 - 5百万円未満', '13': '2百万円以上 - 5百万円未満', '12': '2百万円以上 - 3百万円未満', '11': '2百万円未満'}
{'19600': '1960年度', '19610': '1961年度', '19620': '1962年度', '19630': '1963年度', '19640': '1964年度', '19650': '1965年度', '19660': '1966年度', '19670': '1967年度', '19680': '1968年度', '19690': '1969年度', '19700': '1970年度', '19710': '1971年度', '19720': '1972年度', '19730': '1973年度', '19740': '1974年度', '19750': '1975年度', '19760': '1976年度', '19770': '1977年度', '19780': '1978年度', '19790': '1979年度', '19800': '1980年度', '19810': '1981年度', '19820': '1982年度', '19830': '1983年度', '19840': '1984年度', '19850': '1985年度', '19860': '1986年度', '19870': '1987年度', '19880': '1988年度', '19890': '1989年度', '19900': '1990年度', '19910': '1991年度', '19920': '1992年度', '19930': '1993年度', '19940': '1994年度', '19950': '1995年度', '19960': '1996年度', '19970': '1997年度', '19980': '1998年度', '19990': '1999年度', '20000': '2000年度', '20010': '2001年度', '20020': '2002年度', '20030': '2003年度', '20040': '2004年度', '20050': '2005年度', '20060': '2006年度', '20070': '2007年度', '20080': '2008年度', '20090': '2009年度', '20100': '2010年度', '20110': '2011年度', '20120': '2012年度', '20130': '2013年度', '20140': '2014年度', '20150': '2015年度', '20160': '2016年度', '20170': '2017年度', '20180': '2018年度', '20190': '2019年度', '20200': '2020年度', '20210': '2021年度', '20220': '2022年度', '20230': '2023年度', '20240': '2024年度', '20250': '2025年度'}

In [13]:
df["item_name"] = df["item_code"].map(item_mapping) 
#cat01のcodeと一致するnameを新しい列item_nameとして作る
df["industry_name"] = df["industry_code"].map(industry_mapping)
df["capital_size_name"] = df["capital_size_code"].map(capital_size_mapping)
df["fiscal_year"] = df["time_code"].str[:4].astype(int) # 例えば20250などを2025に変換
df["amount"] = pd.to_numeric(df["amount"], errors="raise") 
# 文字列になっている金額を数値に変換、エラーがあればエラー出て停止

print(df.shape)
df.head()

(540, 10)

,fiscal_year,time_code,industry_code,industry_name,capital_size_code,capital_size_name,item_code,item_name,amount,unit
20,2016,20160,108,製造業,16,1千万円未満,022,資産合計(当期末),10273532,百万円
110,2016,20160,108,製造業,16,1千万円未満,045,売上高(当期末),12488919,百万円
200,2016,20160,108,製造業,16,1千万円未満,051,経常利益(当期末),438726,百万円
290,2016,20160,108,製造業,16,1千万円未満,066,従業員給与(当期末),2169512,百万円
380,2016,20160,108,製造業,16,1千万円未満,085,実物投資(当期末資金需給),544406,百万円

In [14]:
output_columns = [
    "fiscal_year",
    "time_code",
    "industry_code",
    "industry_name",
    "capital_size_code",
    "capital_size_name",
    "item_code",
    "item_name",
    "amount",
    "unit",
]

df = df[output_columns].sort_values(
    ["fiscal_year", "industry_code", "capital_size_code", "item_code"]
)
print(df.shape)
df.head()

(540, 10)

,fiscal_year,time_code,industry_code,industry_name,capital_size_code,capital_size_name,item_code,item_name,amount,unit
20,2016,20160,108,製造業,16,1千万円未満,022,資産合計(当期末),10273532,百万円
110,2016,20160,108,製造業,16,1千万円未満,045,売上高(当期末),12488919,百万円
200,2016,20160,108,製造業,16,1千万円未満,051,経常利益(当期末),438726,百万円
290,2016,20160,108,製造業,16,1千万円未満,066,従業員給与(当期末),2169512,百万円
380,2016,20160,108,製造業,16,1千万円未満,085,実物投資(当期末資金需給),544406,百万円

In [15]:
negative_records = df[df["amount"] < 0]

if not negative_records.empty:
    print("\n負の値を含む財務項目:")
    print(
        negative_records[["item_code", "item_name"]]
        .drop_duplicates()
        .to_string(index=False)
    )

負の値を含む財務項目:
item_code     item_name
      051     経常利益(当期末)
      157      純資産(当期末)
      085 実物投資(当期末資金需給)